const fs = require('node:fs');
const path = require('node:path');
const zlib = require('node:zlib');
const root = path.resolve(__dirname, '../..');
const {PNG} = require(path.join(root, 'apps/ios/node_modules/pngjs'));
const png = PNG.sync.read(fs.readFileSync(path.join(root, 'apps/ios/assets/canopy-ui/mascot-puppet-parts.png')));
// Lossless transport of the original atlas pixels for Expo GL DataTexture.
const encoded = zlib.gzipSync(png.data).toString('base64');
fs.writeFileSync(path.join(root, 'apps/ios/src/ui/canopyTextureData.ts'),
  `// Generated by tools/local/pack_mascot_texture.cjs; original atlas pixels, unchanged.\nexport const textureWidth=${png.width}, textureHeight=${png.height};\nexport const textureBytes='${encoded}';\n`);
